class AdvertisementsController < ApplicationController
  def index
    @advertisements = Advertisement.all
  end

  def show
    #find the ad that corresponds to the id in the params that was passed to show and assign it to @advertisement.
    @advertisement = Advertisement.find(params[:id])
  end

  def new
    #create an instance variable, @advertisement, then assign it an empty ad returned by Post.new.
    @advertisement = Advertisement.new
  end

  def create
  #call Advertisement.new to create a new instance of Advertisement.
     @advertisement = Advertisement.new
     @advertisement.title = params[:advertisement][:title]
     @advertisement.copy = params[:advertisement][:copy]
     @advertisement.price = params[:advertisement][:price]

  # if saving the instance of post to the database was successful, we display a success message using flash[:notice] and redirect the user to the route generated by @post.
  #Redirecting to @post will direct the user to the posts show view.
     if @advertisement.save
  #assign a value to flash[:notice]. The flash hash provides a way to pass temporary values between actions.
  #Any value placed in flash will be available in next action and then deleted.
        flash[:notice] = "Ad was saved."
        redirect_to @advertisement
     else
  #if saving the instance of post was not successful, we display an error message and render the new view again.
        flash[:error] = "There was an error saving the ad. Please try again."
        render :new
     end
  end
end
